# Generated by Django 3.2.9 on 2021-11-27 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_answer_generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutoAnswerQuestions',
            new_name='AutoAnswerQuestionTable',
        ),
        migrations.RenameModel(
            old_name='AutoAnswers',
            new_name='AutoAnswersTable',
        ),
    ]
