# Generated by Django 3.2.9 on 2021-11-27 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_answer_generator', '0002_auto_20211126_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoanswerstable',
            name='parent_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_answer_generator.autoanswerquestiontable'),
        ),
        migrations.AlterField(
            model_name='autoanswerquestiontable',
            name='question_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='autoanswerquestiontable',
            name='ruleset',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='autoanswerstable',
            name='answer_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='autoanswerstable',
            name='answer_label',
            field=models.CharField(max_length=50),
        ),
    ]
