# Generated by Django 3.2.9 on 2021-11-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_answer_generator', '0003_auto_20211127_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoanswerquestiontable',
            name='question_category',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='autoanswerquestiontable',
            name='showExpression',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
