# Generated by Django 3.2.9 on 2021-12-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GWFUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
