# Generated by Django 3.2.9 on 2021-12-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GWFUser',
        ),
    ]
